package se.stageplayer;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.media.MediaPlayer;import android.net.Uri;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import android.database.Cursor;

public class MainActivity extends Activity {
 static final int AUDIO=10,TEXT=11; TextView title,track,textView,playlistLabel,stageState,nextTrack; ScrollView textScroll; SeekBar seek; Button play,stop,prev,next,manage,imp,attach,show,stage,fontDown,fontUp,resetScroll,stageExit; Switch autoNext; LinearLayout topbar,mainLayout,textTools,transport; MediaPlayer mp; Handler h=new Handler(Looper.getMainLooper());
 ArrayList<Item> items=new ArrayList<>(); ArrayList<Playlist> lists=new ArrayList<>(); int current=-1; int playlist=-1; String pendingAttachId=""; SharedPreferences sp; float textSize=25f; boolean stageMode=false;
 static class Item {String id,name,uri,text=""; Item(String i,String n,String u){id=i;name=n;uri=u;}}
 static class Playlist {String name; ArrayList<String> ids=new ArrayList<>(); Playlist(String n){name=n;}}
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);hideBars();sp=getSharedPreferences("data",0);bind();load();}
 void bind(){title=findViewById(R.id.title);track=findViewById(R.id.track);textView=findViewById(R.id.textView);textScroll=findViewById(R.id.textScroll);playlistLabel=findViewById(R.id.playlistLabel);stageState=findViewById(R.id.stageState);nextTrack=findViewById(R.id.nextTrack);seek=findViewById(R.id.seek);play=findViewById(R.id.play);stop=findViewById(R.id.stop);prev=findViewById(R.id.prev);next=findViewById(R.id.next);manage=findViewById(R.id.btnManage);imp=findViewById(R.id.btnImport);attach=findViewById(R.id.btnAttach);show=findViewById(R.id.btnText);stage=findViewById(R.id.btnStage);stageExit=findViewById(R.id.stageExit);mainLayout=findViewById(R.id.mainLayout);textTools=findViewById(R.id.textTools);transport=findViewById(R.id.transport);fontDown=findViewById(R.id.fontDown);fontUp=findViewById(R.id.fontUp);resetScroll=findViewById(R.id.btnResetScroll);autoNext=findViewById(R.id.autoNext);topbar=findViewById(R.id.topbar);
  imp.setOnClickListener(v->pick(AUDIO));attach.setOnClickListener(v->attachText());show.setOnClickListener(v->textScroll.setVisibility(textScroll.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));stage.setOnClickListener(v->toggleStage());stageExit.setOnClickListener(v->toggleStage());for(Button b:new Button[]{prev,play,stop,next}){b.setMinHeight(82);b.setTextSize(b==play?30:23);}fontDown.setOnClickListener(v->{textSize=Math.max(14,textSize-2);textView.setTextSize(textSize);});fontUp.setOnClickListener(v->{textSize=Math.min(50,textSize+2);textView.setTextSize(textSize);});resetScroll.setOnClickListener(v->textScroll.fullScroll(View.FOCUS_UP));
  play.setOnClickListener(v->toggle());stop.setOnClickListener(v->stopPlayback());prev.setOnClickListener(v->move(-1));next.setOnClickListener(v->move(1));manage.setOnClickListener(v->manage());
  seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean u){if(u&&mp!=null)mp.seekTo(p);}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});
 }
 void hideBars(){getWindow().getDecorView().setSystemUiVisibility(5894|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}
 void toggleStage(){stageMode=!stageMode;topbar.setVisibility(stageMode?View.GONE:View.VISIBLE);playlistLabel.setTextSize(stageMode?18:16);playlistLabel.setVisibility(View.VISIBLE);fontDown.setVisibility(stageMode?View.GONE:View.VISIBLE);fontUp.setVisibility(stageMode?View.GONE:View.VISIBLE);show.setVisibility(stageMode?View.GONE:View.VISIBLE);resetScroll.setVisibility(stageMode?View.GONE:View.VISIBLE);textTools.setVisibility(stageMode?View.GONE:View.VISIBLE);autoNext.setVisibility(stageMode?View.GONE:View.VISIBLE);stageExit.setVisibility(stageMode?View.VISIBLE:View.GONE);stage.setText(stageMode?"Redigera":"Scenläge");stageState.setText(stageMode?(mp!=null&&mp.isPlaying()?"SPELAR":"STANDBY"):"");stageState.setTextSize(stageMode?24:14);stageState.setTextColor(Color.WHITE);nextTrack.setTextSize(stageMode?18:14);track.setTextSize(stageMode?32:27);textView.setTextSize(stageMode?Math.max(textSize,28):textSize);hideBars();}
 void pick(int type){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(type==AUDIO?"audio/*":"text/plain");startActivityForResult(i,type);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(d==null||d.getData()==null)return;Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}String name=getName(u);if(r==AUDIO){Item x=new Item(UUID.randomUUID().toString(),name,u.toString());items.add(x);save();choosePlaylistForNew(x);}else{Item x=find(pendingAttachId);if(x!=null){x.text=readText(u);save();render();Toast.makeText(this,"Text kopplad till "+x.name,Toast.LENGTH_SHORT).show();}}}
 String getName(Uri u){String n=null;try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)n=c.getString(i);}}catch(Exception e){}return n==null?"Ljudfil":n;}
 String readText(Uri u){try(InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream o=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);return new String(o.toByteArray(),StandardCharsets.UTF_8);}catch(Exception e){return "Kunde inte läsa textfilen.";}}
 void choosePlaylistForNew(Item x){String[] a=new String[lists.size()+1];a[0]="Ingen playlist";for(int i=0;i<lists.size();i++)a[i+1]=lists.get(i).name;new AlertDialog.Builder(this).setTitle("Lägg till i playlist?").setItems(a,(d,w)->{if(w>0&&!lists.get(w-1).ids.contains(x.id))lists.get(w-1).ids.add(x.id);save();if(current<0){current=items.indexOf(x);render();}}).setOnCancelListener(d->{if(current<0){current=items.indexOf(x);render();}}).show();}
 void attachText(){if(items.isEmpty()){Toast.makeText(this,"Importera ljud först.",Toast.LENGTH_SHORT).show();return;}String[] a=new String[items.size()];for(int i=0;i<items.size();i++)a[i]=items.get(i).name;new AlertDialog.Builder(this).setTitle("Välj låt").setItems(a,(d,w)->{pendingAttachId=items.get(w).id;pick(TEXT);}).show();}
 Item find(String id){for(Item x:items)if(x.id.equals(id))return x;return null;}
 ArrayList<Item> sequence(){ArrayList<Item> r=new ArrayList<>();if(playlist<0){r.addAll(items);return r;}for(String id:lists.get(playlist).ids){Item x=find(id);if(x!=null)r.add(x);}return r;}
 int seqIndex(){ArrayList<Item> s=sequence();if(current<0)return -1;for(int i=0;i<s.size();i++)if(s.get(i).id.equals(items.get(current).id))return i;return -1;}
 void render(){if(current<0||current>=items.size()){track.setText("Ingen låt vald");textView.setText("Ingen text kopplad.");playlistLabel.setText(playlist<0?"Alla låtar":lists.get(playlist).name);stageState.setText(stageMode?"STANDBY":"");nextTrack.setText("Nästa: –");return;}Item x=items.get(current);track.setText(x.name);textView.setText(x.text.length()==0?"Ingen text kopplad.":x.text);textView.setTextSize(textSize);playlistLabel.setText(playlist<0?"Alla låtar":lists.get(playlist).name);stageState.setText(stageMode?(mp!=null&&mp.isPlaying()?"SPELAR":"STANDBY"):"");ArrayList<Item> ss=sequence();int si=seqIndex();if(si>=0&&si+1<ss.size())nextTrack.setText("Nästa: "+ss.get(si+1).name);else nextTrack.setText("Nästa: –");textScroll.fullScroll(View.FOCUS_UP);}
 void toggle(){if(mp!=null&&mp.isPlaying()){mp.pause();play.setText("▶");stageState.setText(stageMode?"PAUSAD":"");return;}if(mp==null)startCurrent();else{mp.start();play.setText("❚❚");stageState.setText(stageMode?"SPELAR":"");}}
 void startCurrent(){if(current<0||current>=items.size())return;release();try{mp=MediaPlayer.create(this,Uri.parse(items.get(current).uri));if(mp==null)throw new Exception();seek.setMax(mp.getDuration());mp.setOnCompletionListener(v->{play.setText("▶");stageState.setText(stageMode?"STANDBY":"");if(autoNext.isChecked())move(1);});mp.start();play.setText("❚❚");stageState.setText(stageMode?"SPELAR":"");tick();}catch(Exception e){Toast.makeText(this,"Kunde inte spela filen.",Toast.LENGTH_SHORT).show();}}
 void tick(){if(mp!=null){try{seek.setProgress(mp.getCurrentPosition());}catch(Exception e){}h.postDelayed(this::tick,250);}}
 void stopPlayback(){if(mp!=null){try{mp.stop();}catch(Exception e){}release();}seek.setProgress(0);play.setText("▶");stageState.setText(stageMode?"STANDBY":"");}
 void release(){if(mp!=null){try{mp.release();}catch(Exception e){}mp=null;}}
 void move(int d){ArrayList<Item> s=sequence();if(s.isEmpty())return;int i=seqIndex();if(i<0)i=0;int n=i+d;if(n<0)n=0;if(n>=s.size()){n=s.size()-1;if(d>0)stopPlayback();}current=items.indexOf(s.get(n));render();if(d!=0&&current>=0&&n!=i)startCurrent();}
 void manage(){String[] a=new String[lists.size()+3];a[0]="+ Ny playlist";a[1]="Alla importerade låtar";a[2]="Redigera spellistor";for(int i=0;i<lists.size();i++)a[i+3]=lists.get(i).name;new AlertDialog.Builder(this).setTitle("Spellistor").setItems(a,(d,w)->{if(w==0)newList();else if(w==1){playlist=-1;current=items.isEmpty()?-1:0;render();}else if(w==2)editPlaylists();else{playlist=w-3;ArrayList<Item>s=sequence();current=s.isEmpty()?-1:items.indexOf(s.get(0));render();}}).show();}
 void newList(){final EditText e=new EditText(this);e.setHint("Namn på playlist");new AlertDialog.Builder(this).setTitle("Ny playlist").setView(e).setPositiveButton("Skapa",(d,w)->{String n=e.getText().toString().trim();if(!n.isEmpty()){lists.add(new Playlist(n));save();}}).setNegativeButton("Avbryt",null).show();}
 void editPlaylists(){if(lists.isEmpty()){Toast.makeText(this,"Inga spellistor ännu.",Toast.LENGTH_SHORT).show();return;}String[] a=new String[lists.size()];for(int i=0;i<lists.size();i++)a[i]=lists.get(i).name;new AlertDialog.Builder(this).setTitle("Välj playlist att redigera").setItems(a,(d,w)->editPlaylist(w)).show();}
 void editPlaylist(int li){Playlist l=lists.get(li);String[] a=new String[l.ids.size()+3];a[0]="+ Lägg till låt";a[1]="Ändra namn";a[2]="Ta bort playlist";for(int i=0;i<l.ids.size();i++){Item x=find(l.ids.get(i));a[i+3]=(i+1)+". "+(x==null?"Saknad fil":x.name);}new AlertDialog.Builder(this).setTitle(l.name).setItems(a,(d,w)->{if(w==0)addToPlaylist(li);else if(w==1)renamePlaylist(li);else if(w==2){lists.remove(li);if(playlist==li)playlist=-1;else if(playlist>li)playlist--;save();}else editEntry(li,w-3);}).show();}
 void addToPlaylist(int li){Playlist l=lists.get(li);ArrayList<String> names=new ArrayList<>();for(Item x:items)if(!l.ids.contains(x.id))names.add(x.name);if(names.isEmpty()){Toast.makeText(this,"Alla låtar finns redan i playlisten.",Toast.LENGTH_SHORT).show();return;}String[] a=names.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Lägg till låt").setItems(a,(d,w)->{String target=names.get(w);for(Item x:items)if(x.name.equals(target)&&!l.ids.contains(x.id)){l.ids.add(x.id);break;}save();}).show();}
 void renamePlaylist(int li){final EditText e=new EditText(this);e.setText(lists.get(li).name);new AlertDialog.Builder(this).setTitle("Ändra namn").setView(e).setPositiveButton("Spara",(d,w)->{String n=e.getText().toString().trim();if(!n.isEmpty())lists.get(li).name=n;save();render();}).setNegativeButton("Avbryt",null).show();}
 void editEntry(int li,int pos){Playlist l=lists.get(li);if(pos<0||pos>=l.ids.size())return;String[] a={"Flytta upp","Flytta ner","Ta bort från playlist"};new AlertDialog.Builder(this).setTitle(find(l.ids.get(pos))==null?"Saknad fil":find(l.ids.get(pos)).name).setItems(a,(d,w)->{if(w==0&&pos>0)Collections.swap(l.ids,pos,pos-1);else if(w==1&&pos<l.ids.size()-1)Collections.swap(l.ids,pos,pos+1);else if(w==2)l.ids.remove(pos);save();}).show();}
 void load(){try{JSONArray a=new JSONArray(sp.getString("items","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);Item x=new Item(o.getString("id"),o.getString("name"),o.getString("uri"));x.text=o.optString("text","");items.add(x);}JSONArray p=new JSONArray(sp.getString("lists","[]"));for(int i=0;i<p.length();i++){JSONObject o=p.getJSONObject(i);Playlist l=new Playlist(o.getString("name"));JSONArray ids=o.optJSONArray("ids");if(ids!=null)for(int j=0;j<ids.length();j++)l.ids.add(ids.getString(j));lists.add(l);}}catch(Exception e){}if(!items.isEmpty()){current=0;render();}}
 void save(){try{JSONArray a=new JSONArray();for(Item x:items){JSONObject o=new JSONObject();o.put("id",x.id);o.put("name",x.name);o.put("uri",x.uri);o.put("text",x.text);a.put(o);}JSONArray p=new JSONArray();for(Playlist l:lists){JSONObject o=new JSONObject();o.put("name",l.name);JSONArray ids=new JSONArray();for(String id:l.ids)ids.put(id);o.put("ids",ids);o.put("name",l.name);o.put("ids",ids);p.put(o);}sp.edit().putString("items",a.toString()).putString("lists",p.toString()).apply();}
 catch(Exception e){}}
 @Override protected void onDestroy(){release();super.onDestroy();}
 @Override public void onBackPressed(){if(stageMode){toggleStage();return;}if(mp!=null){stopPlayback();}else super.onBackPressed();}
}
